### PR TITLE
Bugfix height string overwritten by width string

### PR DESCRIPTION
**Pull request by twify93**

### CODE REVIEW

**Comment by kevinkhill** [comment]
Nice catch, thank you

**Comment by twify93** [comment]
Can you also add it to the `3.1.0-beta2`? I am not quite sure how you handle bugfixes

**Comment by kevinkhill** [comment]
I don't know either! If you make another pull against the 3.1 branch, I'll merge it.

**Comment by twify93** [comment]
Can't you just remove the tag and make it again with the bug fix commit?

**Comment by kevinkhill** [comment]
My bad, I didn't look which branch you made this against. I just looked at the commit and merged.

**Comment by twify93** [comment]
Thanks!

**Comment by kevinkhill** [comment]
tagged 👍

**Pull request merged**
