### PR TITLE
Support for Traversable and ArrayAccess and other fixes

### PR DESCRIPTION
**Pull request by twify93**
Can you check this progress, I see other stuff that I can change, but I want you to check this.

Also there is a fix for the `Utils::nonEmptyString` to allow objects with implemented `__toString`

### CODE REVIEW

**Comment by kevinkhill** [comment]
This looks great! Thank you for taking the time to contribute. :smile:

I will pull your mods into my local copy and do some of my own tests too. I don't want to just click merge right away, because I often break things. (I'm not the best with git)

But, I am confident all is well and that your additions will be beneficial for everyone, thank you again. I will test and report back soon.

**Comment by twify93** [comment]
It's a WIP - work in progress, it's not meant to be merged now. I am still working on other fixes and stuff, because I think there will be other places. I am just asking if this way is the correct, if you want me to follow some conventions and etc.

**Comment by kevinkhill** [comment]
The only thing I wonder about is including illuminate support in composer. Will there be version issues if users are running differ versions of Laravel that also requires support. (I'm not full confident with how composer works either)

**Comment by twify93** [comment]
Well I am not sure how composer will handle it. Basically thou I know that composer can install only 1 version. I tried to use `~5.0` in composer, which means `<=6.0`, but it failed with PHP 5.4 and 5.5.

By the way what d you think of using the `@covers` so building the code coverage, we can see exactly what's tested?

I created a tag 3.0.0-dev with my changes and tried to install it in Laravel 5.3 project:
```
- The requested package khill/lavacharts 3.0.0-dev exists as khill/lavacharts[1.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.1.0, 2.2.0, 2.2.1, 2.3.0, 2.4.0, 2.4.1, 2.4.2, 2.5.0, 2.5.1, 2.5.10, 2.5.2, 2.5.3, 2.5.4, 2.5.5, 2.5.6, 2.5.7, 2.5.8, 2.5.9, 2.5.x-dev, 3.0.0, 3.0.0-beta1, 3.0.0-beta2, 3.0.0-rc1, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.x-dev, 3.1.0-alpha1, 3.1.0-alpha2, 3.1.0-alpha3, 3.1.0-beta1, 3.1.x-dev, dev-master] but these are rejected by your constraint.
```

Also I can also write 2 classes implementing ArrayAccess and Traversable, so `illuminate/support` is not required.

**Comment by kevinkhill** [comment]
I see, my mistake. I have no issue add dev dependencies. (you should see the 3.1 branch package.json!) Anyways, I will try to poke around through your code soon.

**Comment by kevinkhill** [comment]
Could you post some examples of what you are trying to accomplish? I want to see what you are going for.

**Comment by twify93** [comment]
Well I did couple of things, except the Traversable/ArrayAccess thing.

1. [https://github.com/kevinkhill/lavacharts/pull/171/files#diff-b8529ff0ee2d64fc06becdbbc32de0bdR118](validStringProvider()) - for strings you can also use objects implementing `__toStrong()` there are other places, but I will check later this week
2. You can now pass Collections(laravel) or objects implementing Traversable to `addRows()` [https://github.com/kevinkhill/lavacharts/pull/171/files#diff-b8529ff0ee2d64fc06becdbbc32de0bdR182](traversableProvider())
3. You can pass `ArrayAccess` objects to `addRow` and `addRows` (again for easy usage I use laravel's collection) [https://github.com/kevinkhill/lavacharts/pull/171/files#diff-b8529ff0ee2d64fc06becdbbc32de0bdR195](arrayAccessProvider)
4. I also added support for `Traversable` in `Util::nonEmptyStringInArray()`, basically you can send again Collection with again Objects implementing `__toString()` and it will work check the DataProviders `iterableWithStrings`, `iterableInArrayWithGoodData`, `iterableInArrayWithBadData`

**Comment by kevinkhill** [comment]
Looking good. I did clone your work to my laptop, but haven't looked into it yet.

**Comment by twify93** [comment]
With this you don't need the Laravel Collection package, because we basically support it natively with these changes. But you can leave it for backward compatibility and remove the Collection stuff and just use these methods again. I hope I can take a look these days..

**Comment by twify93** [comment]
If you have time, check the changes, if you want me to change something just tell me, so we can merge it. I think these changes are enough for now. This literally removes the need for the other package, but I still need to check the other places.

**Comment by kevinkhill** [comment]
I don't really have time to dig into this, but I trust you that it works as expected, so I'll just merge it. I hate just leaving it hanging.

**Comment by kevinkhill** [comment]
Now my only task will be to make sure I pull your updates into the 3.1 branch so they don't get lost. 😄

**Comment by twify93** [comment]
I honestly don't remember what I did and what was left, I think I wanted to add some more stuff, I will try to check it this weekend.

**Pull request merged**
