### PR TITLE
Naming fix: "viewWindowMin" should be just "min". Same for "max"

### PR DESCRIPTION
**Pull request by antoniotajuelo**
View
https://developers.google.com/chart/interactive/docs/gallery/areachart
hAxis.viewWindow.min

### CODE REVIEW

**Comment by kevinkhill** [comment]
These changes provide the working functionality you were looking for?

**Comment by antoniotajuelo** [comment]
Yes.

https://github.com/antoniotajuelo/lavacharts/commit/650df1ee99c15dc375d3274b4ea9fa4ad97d1f71 Without these naming changes, the vAxis/hAxis.viewWindow.min/mas settings won't work.

https://github.com/antoniotajuelo/lavacharts/commit/980a0ffa209bcecb37b0e7999e437b28fe721dcf Sometimes you will want to only set the max or min property, so the library should not require both values to be set.

**Comment by kevinkhill** [comment]
Thanks for clearing this up for me :+1:

**Comment by antoniotajuelo** [comment]
No problem :)

**Pull request merged**
